[package]
name = "polyegg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]
path = "src/polyegg.rs"

[dependencies]
egg = "0.9.5"
cxx = "1.0"
